source_identifier: exp=mfx100852324,run=51
#source_identifier: exp=mfx100848724,run=51

skip_incomplete_events: True

data_sources:
    timestamp:
        type: Psana2Timestamp

    detector_data:
        type: Psana2DetectorInterface
        psana_name: jungfrau
        psana_fields: raw.calib             # Use raw.calib for calibrated data

        #    assembled_detector_data:
        #        type: Psana2DetectorInterface
        #        psana_name: jungfrau
        #        psana_fields: raw.image

    photon_wavelength:
        type: Psana2DetectorInterface
        psana_name: "SIOC:SYS0:ML00:AO192"

    detector_geometry:
        type: Psana2DetectorInterface
        psana_name: "jungfrau"
        psana_fields: [
            "_detid",                     # Detector ID
            "raw._det_geotxt_default"     # Geometry data
        ]
        dtype: str

    beam_data:                            # Optional
        type: Psana2DetectorInterface
        psana_name: "ebeamh"
        psana_fields: [
            "raw.ebeamUndAngX",           # Angle X
            "raw.ebeamUndAngY",           # Angle Y
            "raw.ebeamUndPosX",           # Pos X
            "raw.ebeamUndPosY",           # Pos Y
            "raw.ebeamL3Energy"           # Beam energy
        ]

    run_info:
        type: Psana2RunInfo

event_source:
    type: Psana2EventSource

processing_pipeline:
    type: BatchProcessingPipeline
    batch_size: 1

data_serializer:
    type: SimplonBinarySerializer
    data_source_to_serialize: detector_data
    polarization_fraction: 0
    polarization_axis: [1.0, 0.0, 0.0]
    data_collection_rate: "120Hz"
    detector_name: "jungfrau"
    detector_type: "AreaDetector"

data_handlers:
  - type: BinaryDataStreamingDataHandler
    urls: 
        - "tcp://134.79.23.43:5000" #127.0.0.1:12321"
    role: client
    library: nng 
    #library: zmq
    socket_type: push
