source_identifier: exp=tmox1016823,run=44
skip_incomplete_events: true

data_sources:
    timestamp:
        type: Psana2Timestamp

#    beam_energy:
#        type: Psana2DetectorInterface
#        psana_name: ebeamh
#        psana_fields: raw.ebeamL3Energy
#
    tmo_fzppiranha:
        type: Psana2DetectorInterface
        psana_name: tmo_fzppiranha
        psana_fields: raw.raw

#    tmo_atmpiranha:
#        type: Psana2DetectorInterface
#        psana_name: tmo_atmpiranha
#        psana_fields: raw.raw
#
    pulse_energy:
        type: Psana2DetectorInterface
        psana_name: gmd
        psana_fields: raw.milliJoulesPerPulse

    xpulse_energy:
        type: Psana2DetectorInterface
        psana_name: xgmd
        psana_fields: raw.milliJoulesPerPulse

    mrco_hsd_peaks:
        type: Psana2DetectorInterface
        psana_name: mrco_hsd
        psana_fields: raw.peaks

    mrco_hsd_waveforms:
        type: Psana2DetectorInterface
        psana_name: mrco_hsd
        psana_fields: raw.waveforms

event_source:
    type: Psana2EventSource

processing_pipeline:
    type: BatchProcessingPipeline
    batch_size: 10

data_serializer:
    type: Hdf5BinarySerializer
    compression_level: 3
    compression: zfp
    fields:
        timestamp: /timestamp
        tmo_fzppiranha: /fzpppiranha
        pulse_energy: /pulseenergy
        xpulse_energy: /xpulseenergy
        mrco_hsd_peaks: /peaks
        mrco_hsd_waveforms: //waveform

data_handlers:
  - type: BinaryFileWritingDataHandler
    write_directory: workspace/output

# - type: BinaryDataStreamingDataHandler
#   urls:
#       - "tcp://sdfdtn003:5000"
#   role: client
#   library: nng
#   socket_type: push
