source_identifier: exp=xpply5120:run=318
skip_incomplete_events: false

event_source:
    type: Psana1EventSource

data_sources:
    timestamp:
        type: Psana1Timestamp

    detector_data:
        type: Psana1AssembledAreaDetector
        psana_name: jungfrau1M

    ipm2sum:
        type: Psana1BbmonDetectorTotalIntensity
        psana_name: XPP-SB2-BMMON

    ipm3sum:
        type: Psana1BbmonDetectorTotalIntensity
        psana_name: XPP-SB3-BMMON

    diodeUchannel:
        type: Psana1IpmDetector
        psana_name: XppEnds_Ipm0
        psana_function: channel

    timetool_ampl:
        type: Psana1PV
        psana_name: "XPP:TIMETOOL:AMPL"

    timetool_delay:
        type: Psana1PV
        psana_name: "XPP:TIMETOOL:FLTPOS"

    timetool_delay_ps:
        type: Psana1PV
        psana_name: "XPP:TIMETOOL:FLTPOS_PS"

    usb_encoder_2:
        type: Psana1UsdUsbDetector
        psana_name: "XPP-USB-ENCODER-02"
        psana_function: values

    evr_codes:
        type: Psana1EvrCodes
        psana_name: evr0

processing_pipeline:
    type: BatchProcessingPipeline
    batch_size: 100

data_serializer:
    type: Hdf5BinarySerializer
    compression_level: 3
    compression: zfp
    fields:
        timestamp: /data/timestamp
        detector_data: /data/data
        ipm2sum: /data/ipm2sum
        ipm3sum: /data/ipm3sum
        diodeUchannel: /data/diodeuchannel
        timetool_ampl: /data/timetoolampl
        timetool_delay: /data/timetooldelay
        timetool_delay_ps: /data/timetooldelayps
        usb_encoder_2: /data/usbencoder2
        evr_codes: /data/evrcodes

data_handlers:
  - type: BinaryFileWritingDataHandler
    file_prefix: "xpply5120-run31"
    file_suffix: h5
    write_directory: workspace/output

# - type:  BinaryDataStreamingDataHandler
#   urls:
#    #  - "tcp://sdfdtn003:5000"
#       - "tcp://127.0.0.1:12321"
#   role: client
#   library: nng
#   socket_type: push
