source_identifier: ""
skip_incomplete_events: false

event_source:
    type: InternalEventSource
    number_of_events_to_generate: 76

data_sources:
    random:
        type: GenericRandomNumpyArray
        array_shape: 20,2
        array_dtype: float32

processing_pipeline:
    type: BatchProcessingPipeline
    batch_size: 10

data_serializer:
    type: Hdf5BinarySerializer
    compression_level: 3
    compression: null
    fields:
        random: /data/random

data_handlers:
    - type: BinaryFileWritingDataHandler
      file_prefix: ""
      file_suffix: h5
      write_directory: workspace/output

#   - type: BinaryDataStreamingDataHandler
#     urls:
#         - "tcp://127.0.0.1:12321"
#     role: client
#     library: nng
#     socket_type: push
