source_identifier: exp=mfx100903824:run=27
skip_incomplete_events: false

event_source:
    type: Psana1EventSource

data_sources:
    timestamp:
        type: Psana1Timestamp

    detector_data:
        type: Psana1AssembledAreaDetector
        psana_name: epix10k2M


    photon_wavelength:
        type: Psana1PV
        psana_name: "SIOC:SYS0:ML00:AO192"

processing_pipeline:
    type: PeaknetPreprocessingPipeline
    batch_size: 16
    target_height: 1920
    target_width: 1920
    pad_style: center
    add_channel_dim: true
    num_channels: 1

data_serializer:
    type: HDF5BinarySerializer
    compression_level: 3
    compression: zfp
    fields:
        timestamp: /data/timestamp
        detector_data: /data/data
        photon_wavelength: /data/wavelength

data_handlers:
    - type: BinaryDataStreamingDataHandler
      urls:
          - "tcp://sdfada001:12321"
      role: client
      library: nng
      socket_type: push
