source_identifier: exp=mfx100852324,run=355
skip_incomplete_events: true

event_source:
    type: Psana2EventSource

data_sources:
    timestamp:
        type: Psana2Timestamp

    detector_data:
        type: Psana2DetectorInterface
        psana_name: jungfrau
        psana_fields: raw.raw             # Use raw.calib for calibrated data

    assembled_detector_data:
        type: Psana2DetectorInterface
        psana_name: jungfrau
        psana_fields: raw.image

    random:
        type: GenericRandomNumpyArray
        array_shape: 4,4,4
        array_dtype: float32

    photon_wavelength:
        type: Psana2DetectorInterface
        psana_name: "SIOC:SYS0:ML00:AO192"

processing_pipeline:
    type: BatchProcessingPipeline
    batch_size: 10

data_serializer:
    type: Hdf5BinarySerializer
    compression_level: 3
    compression: zfp
    fields:
        timestamp: /timestamp
        detector_data: /data
        assembled_detector_data: /assembled
        photon_wavelength: /wavelength
        random: /drandom

data_handlers:
  - type: BinaryFileWritingDataHandler
    write_directory: workspace/output

# - type: BinaryDataStreamingDataHandler
#   urls:
#       - "tcp://sdfdtn003:5000"
#   role: client
#   library: nng
#   socket_type: push
